assignment2b: assignment2b.o processing.o
	g++ assignment2b.cpp processing.cpp -o assignment2b
assignment2b.o:
	g++ -c assignment2b.cpp
processing.o:
	g++ -c processing.cpp
clean:
	rm -rf assignment2b *.o 
