assignment3: assignment3.o transformer.o Autobot.o Decepticon.o Minicon.o Gun.o Armour.o
	g++ assignment3.cpp transformer.cpp Autobot.cpp Decepticon.cpp Minicon.cpp Gun.cpp Armour.cpp -o assignment3
assignment3.o:
	g++ -c assignment3.cpp

transformer.o:
	g++ -c transformer.cpp

Autobot.o:
	g++ -c Autobot.cpp

Decepticon.o:
	g++ -c Decepticon.cpp

Minicon.o:
	g++ -c Minicon.cpp

Gun.o:
	g++ -c Gun.cpp

Armour.o:
	g++ -c Armour.cpp

clean:
	rm -rf assignment3 *.o