assignment2a: assignment2a.o massive_reverse.o
	g++ assignment2a.cpp massive_reverse.cpp -o assignment2a
assignment2a.o:
	g++ -c assignment2a.cpp
massive_reverse.o:
	g++ -c massive_reverse.cpp
clean:
	rm -rf assignment2a *.o test1.bin *.o
